ci: added GDScript type checking
Note that running the editor once in headless mode is needed to generate the `.godot` metadata directory for the project. This contains the ClassDB that Godot uses for typing recognition, among other things.

diff --git a/.github/workflows/check-source-code.yaml b/.github/workflows/check-source-code.yaml
--- a/.github/workflows/check-source-code.yaml
+++ b/.github/workflows/check-source-code.yaml
@@ -131,3 +131,18 @@ jobs:
               exit 1
             fi
           done
+
+      - name: Generate ClassDB
+        run: |
+          godot --headless --editor --quit
+
+      - name: Type Check GDScript Files
+        run: |
+          find . -name "*.gd" -not -path "./addons/*" | while read -r file; do
+            echo "Type checking: $file"
+
+            if ! godot --headless --check-only --script "$file"; then
+              echo "::error file=$file::Type checking failed on this file."
+              exit 1
+            fi
+          done
